### PR TITLE
adding http client

### PR DESCRIPTION
**Pull request by jose-zenledger**
https://zenledger.atlassian.net/browse/DREAM-7

### CODE REVIEW

**Comment by andrewhare** [comment]
This looks cool. What does it buy us over `http.Client`?

**Comment by jose-zenledger** [comment]
@andrewhare It's very similar to and uses the stdlib one, really just convenience to lessen the amount of code and dealing directly with a round tripper setup. It does enforce that all timeouts are set which is nice because I've seen it hang by forgetting to set some of them. One thing that I will add is auto adding metrics so we can get the traces and it will configure the round tripper to send the required info to do distributed tracing. Added bonus is if we want to change out the http client to a different one, we can do so just in this package making refactoring a lot easier

**Comment by andrewhare** [comment]
@jose-zenledger That makes sense (I like the good defaults). 

What I don't like is that we are introducing a new package that isn't immediately known and we have to maintain and document whereas the types in `http` are known and already documented.

I think a better approach (if we want to be flexible) would be to inject the dependency instead of abstract it. Create a function like this: 

```go
func ConfigureHTTPClient(c *http.Client) { /* ... */ }
```

Services would then create an http client and pass it into this function to get configured with the good defaults. Then, if we wanted to use a different client, we would create another function:

```go
func ConfigureOtherHTTPClient(c *other.Client) { /* ... */ }
```

This would allow us to upgrade as needed instead of making a base-level change that would instantly upgrade all services without us knowing what regressions we might be creating in changing the semantics of every service's client.

**Comment by jose-zenledger** [comment]
@andrewhare sounds good, I just made this from common stuff that I've had to do in the past but definitely get the concern. Let's put this PR on ice, implement the client that talks to the apis in kensho and then see what can be dried up from that work

**Comment by andrewhare** [comment]
> @andrewhare sounds good, I just made this from common stuff that I've had to do in the past but definitely get the concern. Let's put this PR on ice, implement the client that talks to the apis in kensho and then see what can be dried up from that work

That sounds like a good plan :+1:

**Comment by jose-zenledger** [comment]
I'm going to merge in just to close the ticket, if we don't use we can remove after implementing in kensho or refactor accordingly

**Pull request merged**
